package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.AppointmentRequest;
import edu.ncsu.csc.iTrust2.models.User;

/**
 * Repository for interacting with AppointmentRequest model. Method
 * implementations generated by Spring
 * 
 * @author Kai Presler-Marshall
 *
 */
public interface AppointmentRequestRepository extends JpaRepository<AppointmentRequest, Long> {

    /**
     * Find all AppointmentRequests for the provided Patient
     * 
     * @param patient
     *            Patient to find ARs for
     * @return Matching ARs
     */
    public List<AppointmentRequest> findByPatient ( User patient );

    /**
     * Find all AppointmentRequests for the provided HCP
     * 
     * @param hcp
     *            HCP to find ARs for
     * @return Matching ARs
     */
    public List<AppointmentRequest> findByHcp ( User hcp );

    /**
     * Find all AppointmentRequests for both a given HCP and Patient.
     * 
     * @param hcp
     *            HCP to search by
     * @param patient
     *            Patient to search by
     * @return Matching ARs
     */
    public List<AppointmentRequest> findByHcpAndPatient ( User hcp, User patient );

}
