package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.BasicHealthMetrics;

/**
 * Repository for interacting with BasicHealthMetrics model. Method
 * implementations generated by Spring
 * 
 * @author Kai Presler-Marshall
 *
 */
public interface BasicHealthMetricsRepository extends JpaRepository<BasicHealthMetrics, Long> {

}
