package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.Diagnosis;
import edu.ncsu.csc.iTrust2.models.OfficeVisit;

/**
 * Repository for interacting with Diagnosis model. Method implementations
 * generated by Spring
 * 
 * @author Kai Presler-Marshall
 *
 */
public interface DiagnosisRepository extends JpaRepository<Diagnosis, Long> {

    /**
     * Find Diagnoses for a given OfficeVisit
     * 
     * @param visit
     *            Visit to search by
     * @return Matching Diagnoses
     */
    public List<Diagnosis> findByVisit ( OfficeVisit visit );

}
