package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.Hospital;

/**
 * Repository for interacting with Hospital model. Method implementations
 * generated by Spring
 * 
 * @author Kai Presler-Marshall
 *
 */
public interface HospitalRepository extends JpaRepository<Hospital, String> {

    /**
     * Find a hospital with the provided name
     * 
     * @param name
     *            Name of the hospital
     * @return Matching hospital, if found
     */
    public Hospital findByName ( String name );

}
