package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.ICDCode;

/**
 * Repository for interacting with ICDCode model. Method implementations
 * generated by Spring
 * 
 * @author Kai Presler-Marshall
 *
 */
public interface ICDCodeRepository extends JpaRepository<ICDCode, Long> {

    /**
     * Finds an ICDCode by the provided code
     * 
     * @param code
     *            Code to search by
     * @return Matching code, if any
     */
    public ICDCode findByCode ( String code );

    /**
     * Find all ophthalmology ICD codes
     * 
     * @return matching codes
     */
    public List<ICDCode> findByIsOphthalmologyIsTrue ();

    /**
     * Find non-ophthalmology ICD codes
     * 
     * @return matching codes
     */
    public List<ICDCode> findByIsOphthalmologyIsFalseOrIsOphthalmologyIsNull ();
}
