package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.Payment;

/**
 * Repository for interacting with Payment model. Method implementations
 * generated by Spring
 *
 * @author yli246
 *
 */
public interface PaymentRepository extends JpaRepository<Payment, Long> {
}
