package edu.ncsu.csc.iTrust2.repositories;

import edu.ncsu.csc.iTrust2.models.Personnel;
import edu.ncsu.csc.iTrust2.models.User;

/**
 * Repository for interacting with Personnel model. Method implementations
 * generated by Spring
 *
 * @author Kai Presler-Marshall
 * @param <T>
 *            Type of user
 */
public interface PersonnelRepository <T extends User> extends UserRepository<Personnel> {

}
