package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.SatisfactionSurvey;

/**
 * Repository for interacting with AppointmentRequest model. Method
 * implementations generated by Spring
 *
 * @author Unascribed
 *
 */
public interface SatisfactionSurveyRepository extends JpaRepository<SatisfactionSurvey, Long> {

    /**
     * Find all SatisfactionSurveys for the given HCP
     *
     * @param hcp
     *            HCP username to search by
     * @return Matching SatisfactionSurveys
     */
    public List<SatisfactionSurvey> findByHcpUsername ( String hcp );

    /**
     * Find all SatisfactionSurveys for the given Patient
     *
     * @param patient
     *            Patient username to search by
     * @return Matching SatisfactionSurveys
     */
    public List<SatisfactionSurvey> findByPatientUsername ( String patient );

    /**
     * Find all SatisfactionSurveys for the given HCP and Patient
     *
     * @param hcp
     *            HCP username to search by
     * @param patient
     *            Patient username to search by
     * @return Matching SatisfactionSurveys
     */
    public List<SatisfactionSurvey> findByHcpUsernameAndPatientUsername ( String hcp, String patient );

}
