package edu.ncsu.csc.iTrust2.repositories;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.User;
import edu.ncsu.csc.iTrust2.models.VaccineAppointmentRequest;

/**
 * Repository for interacting with VaccineAppointmentRequest model. Method
 * implementations generated by Spring
 *
 * @author accline2, mjcheim
 *
 */
public interface VaccineAppointmentRequestRepository extends JpaRepository<VaccineAppointmentRequest, Long> {

    /**
     * Find all AppointmentRequests for the provided Patient
     *
     * @param patient
     *            Patient to find ARs for
     * @return Matching ARs
     */
    public List<VaccineAppointmentRequest> findByPatient ( User patient );

    /**
     * Find all AppointmentRequests for the provided HCP
     *
     * @param hcp
     *            HCP to find ARs for
     * @return Matching ARs
     */
    public List<VaccineAppointmentRequest> findByHcp ( User hcp );

    /**
     * Find all AppointmentRequests for both a given HCP and Patient.
     *
     * @param hcp
     *            HCP to search by
     * @param patient
     *            Patient to search by
     * @return Matching ARs
     */
    public List<VaccineAppointmentRequest> findByHcpAndPatient ( User hcp, User patient );

}
