package edu.ncsu.csc.iTrust2.repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import edu.ncsu.csc.iTrust2.models.VaccineType;

/**
 * Repository for interacting with VaccineType model. Method implementations
 * generated by Spring
 *
 * @author mjcheim, accline2
 *
 */
public interface VaccineTypeRepository extends JpaRepository<VaccineType, Long> {
    /**
     * Check if a vaccine exists with the given code
     *
     * @param name
     *            name to search by
     * @return If the vaccine exists
     */
    public boolean existsByName ( String name );

    /**
     * Find a vaccine by the given code
     *
     * @param name
     *            name to search by
     * @return The vaccine, if it exists
     */
    public VaccineType findByName ( String name );

}
